AWSTemplateFormatVersion: '2010-09-09'
Description: CORS Proxy with bundled node_modules

Resources:
  NodeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  NodeLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cors-proxy
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt NodeLambdaRole.Arn
      Code:
        ZipFile: "dummy"  # Will be replaced by direct upload
      Environment:
        Variables:
          NODE_ENV: production
          BLOCKED_HOSTS: 'localhost,127.0.0.1,169.254.169.254'
      MemorySize: 512
      Timeout: 15

Outputs:
  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref NodeLambdaFunction