name: Deploy Lambda
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name node-lambda \
            --capabilities CAPABILITY_IAM

      - name: Zip and update Lambda code
        run: |
          zip function.zip index.js
          aws lambda update-function-code \
            --function-name node-lambda \
            --zip-file fileb://function.zip